Repository deepfakes/faceswap, pull requests merged in 2018-10, with the labels that each got.

#510 Fixed face extract with dlib on OS X
  lib/gpu_stats.py
  setup.py
  tools/cli.py
Labels: bugfix, code to integrate, feedback wanted

#524 fix docker run command
  INSTALL.md
Labels: feedback wanted

#512 Add timelapse functionality
  lib/cli.py
  lib/training_data.py
  lib/utils.py
  scripts/train.py
Labels: code to integrate, feature, feedback wanted
