Repository deepfakes/faceswap, pull requests merged in 2018-04, with the labels that each got.

#363 Adding new tool effmpeg ("easy"-ffmpeg) with gui support. Extend gui functionality to support filetypes.
  lib/cli.py
  scripts/gui.py
  scripts/train.py
  tools.py
  tools/effmpeg.py
  tools/sort.py
Labels: code to integrate, enhancement, feature

#371 Model backup bugfix
  lib/utils.py
  plugins/Model_GAN/Model.py
  plugins/Model_GAN128/Model.py
  plugins/Model_IAE/AutoEncoder.py
  plugins/Model_LowMem/AutoEncoder.py
  plugins/Model_Original/AutoEncoder.py
Labels: bugfix, test needed

#367 cli/scripts Refactor
  faceswap.py
  lib/cli.py
  lib/utils.py
  scripts/convert.py
  scripts/extract.py
  scripts/fsmedia.py
  scripts/gui.py
  scripts/train.py
Labels: code to integrate, feedback wanted

#380 Fixes processing of the list-of-angles rotation parameter
  scripts/fsmedia.py
Labels: bugfix, code to integrate

#379 Fixed 'histogram' CLI parameter spelling
  lib/cli.py
Labels: bugfix, code to integrate
